# fly.toml app configuration file generated for zpibackend on 2023-11-26T13:22:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zpibackend"
primary_region = "waw"

[env]
  SPRING_DATASOURCE_PASSWORD = "wgglGsK5wIjVyVF"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://zpibackend-db.flycast:5432/zpibackend?sslmode=disable"
  SPRING_DATASOURCE_USERNAME = "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO = "create"
  swap_size_mb = "512"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
