server:
  address: 0.0.0.0
  tomcat:
    threads:
      max: 4

keycloak:
  realm: zpi
  auth-server-url: https://keycloak-docker.fly.dev/
  resource: spring-app
  bearer-only: true
  ssl-required: NONE

spring:
  datasource:
    password: docker
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
